service: hangouts-chat-github-integration

provider:
  name: aws
  runtime: nodejs10.x
  usagePlan:
    throttle:
      burstLimit: 100
      rateLimit: 50

package:
  exclude:
    - examples/*
    - ./*.env
    - LICENSE
    - package*.json
    - README.md
    - test.js
    - .eslintrc.yml

functions:
  handleEvents:
    handler: handlers.handleEvents
    memorySize: 128
    timeout: 10
    environment:
      WHITELISTED_SPACES: AAAAdVekrco AAAAdLWzaKg
    events:
      - http:
          path: /v1/spaces/{spaceId}/messages
          method: post
          cors: true
